[workspace]
authors = ["Shuqi XIAO <xiaosq2000@gmail.com>"]
channels = ["conda-forge"]
name = "record3d"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
postinstall = "python setup.py install"

[dependencies]
python = "3.11.*"
cmake = "*"
setuptools = "*"
numpy = "*"
opencv = "*"

[feature.ros-noetic]
channels = ["robostack-noetic", "conda-forge"]

[feature.ros-noetic.dependencies]
ros-noetic-desktop = "*"

[environments]
default = { features = ["ros-noetic"] }
